package com.thoughtworks.cyclerental.service;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.thoughtworks.cyclerental.dto.Customer;
import com.thoughtworks.cyclerental.dto.Cycle;
import com.thoughtworks.cyclerental.dto.Invoice;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class RentalServiceTest {
    List<Cycle> cycles = new ArrayList<>();

    HashMap<Cycle, Customer> rentals = new HashMap<>();

    List<Customer> customers = new ArrayList<Customer>();

    RentalService rentalSrv;


    List<Invoice> invoices = new ArrayList<Invoice>();
    @Test public void testSomeLibraryMethod() {
        assertEquals("1|BSA SLR|BSA|10.000000 per day\n" +
                "2|Mountain Bike 101|MDX|100.000000 for 10 days. 10.000000 after each day.\n",rentalSrv.printCyclesReport("MDX") );
    }

    @After
    public void tearDown() throws Exception {

    }

    @Before
    public void setUp() throws Exception {
        cycles.add(new Cycle(1, "BSA", "BSA SLR", 10.0));
        cycles.add(new Cycle(2, "MDX", "Mountain Bike 101", 100.0, 10, 10.0));
        customers.add(new Customer(1, "Kashi"));
        rentalSrv = new RentalService(cycles, customers);
    }
}
